// Constants mirroring apps/web/src/utils/constants.ts.
import type { PresetType } from '../api/client';

export const PRESET_DISPLAY_NAME: Record<PresetType, string> = {
  bangumi: '番剧'
};

export const types = ['动画', '合集', '音乐', '日剧', 'RAW', '漫画', '游戏', '特摄', '其他'];

export const DisplayTypeColor: Record<string, string> = {
  动画: 'text-red-600',
  合集: 'text-[#ff0000]',
  漫画: 'text-green-600',
  音乐: 'text-purple-600',
  日剧: 'text-blue-600',
  RAW: 'text-[#ffa500]',
  游戏: 'text-[#0eb9e7]',
  特摄: 'text-[#a52a2a]',
  其他: 'text-base-800'
};

// Generated by the same SQL as the original (fansubs with recent activity)
export const fansubs = [
  'ANi',
  'LoliHouse',
  '喵萌奶茶屋',
  'Prejudice-Studio',
  '绿茶字幕组',
  '桜都字幕组',
  '雪飄工作室(FLsnow)',
  '三明治摆烂组',
  '北宇治字幕组',
  '魔星字幕团',
  '拨雪寻春',
  '爱恋字幕社',
  'SweetSub',
  '樱桃花字幕组&sakura-hana',
  '千夏字幕组',
  '沸班亚马制作组',
  '动漫国字幕组',
  '天月動漫&發佈組',
  '猎户发布组',
  '天使动漫论坛',
  '幻樱字幕组',
  '六四位元字幕組',
  '悠哈璃羽字幕社',
  'DBD制作组',
  'TSDM字幕組',
  '百冬練習組',
  'GMTeam',
  '银色子弹字幕组',
  'VCB-Studio',
  '夜莺家族',
  '亿次研同好会',
  '丸子家族',
  '风之圣殿',
  '云光字幕组',
  '黑白字幕组',
  '驯兽师联盟',
  '星空字幕组',
  '极影字幕社',
  'MingYSub',
  'H-Enc',
  '离谱Sub',
  '云歌字幕组',
  'PorterRAWS',
  '豌豆字幕组',
  '隣天使字幕组',
  'Kirara Fantasia'
];

export const NAV_HEIGHT = 66;
export const SEARCH_TOP = 128;
export const HERO_HEIGHT = 300;

export const SITE_TITLE = 'Anime Garden 動漫花園資源網镜像站 动漫花园动画 BT 资源聚合站';

export const CalendarSeasonMonths = [1, 4, 7, 10];

export const CalendarSeasonMap: Record<number, { emoji: string; name: string; label: string }> = {
  1: { emoji: '❄️', name: '冬季新番', label: '冬季' },
  4: { emoji: '🌸', name: '春季新番', label: '春季' },
  7: { emoji: '☀️', name: '夏季新番', label: '夏季' },
  10: { emoji: '🍁', name: '秋季新番', label: '秋季' }
};

export function getCalendarSeason(season?: string) {
  if (!season) {
    return { season: '', year: '', month: 0, emoji: '', name: '新番', label: '选择季度', title: '新番' };
  }
  const [year, monthText] = season.split('-');
  const month = Number(monthText);
  const meta = CalendarSeasonMap[month] ?? { emoji: '', name: `${month} 月新番`, label: `${month} 月` };
  return { season, year, month, ...meta, title: `${year} · ${meta.name}` };
}

// Get the active season based on current month (e.g. "2026-07")
export function getActiveSeason(now = new Date()) {
  const year = now.getFullYear();
  const month = now.getMonth() + 1;
  const months = [1, 4, 7, 10];
  let m = 1;
  for (const candidate of months) {
    if (month >= candidate) m = candidate;
  }
  return `${year}-${String(m).padStart(2, '0')}`;
}

// -- getPikPakUrlChecker: magnet -> pikpak offline download link (keepshare)
export const KEEPSHARE_ID = 'gv78k1oi';

export function getPikPakUrlChecker(magnet: string) {
  return `https://keepshare.org/share/${KEEPSHARE_ID}?url=${encodeURIComponent(magnet)}`;
}

// Format a size number (bytes) like the original parseSize
export { parseSize } from '../api/client';

// Head meta for the calendar page.
export function getCalendarSeasonHead(season?: string) {
  const calendarSeason = getCalendarSeason(season);
  const titlePrefix = calendarSeason.season ? `${calendarSeason.title}动画周历` : '动画周历';
  return {
    title: `${titlePrefix} | ${SITE_TITLE}`,
    description: `${titlePrefix}, 动画每周播出时间表, ${SITE_TITLE}`
  };
}
