// Package anipar is a Go port of the TypeScript anipar anime-title parser
// (packages/anipar in the AnimeGarden monorepo). It implements
//
//	Parse(title string, fansub string) *ParseResult
//
// with exact behavioral parity to the TypeScript `parse(title, { fansub })`.
//
// # Verification
//
// The test suite replays every one of the 12,356 input→output pairs from the
// original test assets (packages/anipar/test/__assets__/*.csv) against the
// expected outputs. Because the original snapshots were rendered by vitest's
// object serializer (alphabetical key order, raw quotes), the fixtures in
// testdata/ were regenerated by running the real TypeScript bundle over the
// original CSV inputs. A separate check confirmed the regenerated values are
// byte-identical to the original snapshots (modulo key order). All 12,356
// fixtures pass.
//
// # Documented deviations
//
//  1. Regex engine: the original uses JavaScript regex (PCRE-style). Go uses
//     RE2, so:
//     - Named groups were translated to numbered groups.
//     - `\s` was rewritten to an explicit character class matching exactly the
//     JavaScript `\s` set (Go's `\s` misses several Unicode spaces). No
//     lookahead or backreferences appear in the original patterns.
//     - All original patterns compile under RE2 unchanged otherwise.
//  2. String slice semantics: JavaScript slices strings by UTF-16 code units;
//     Go slices by bytes. This is equivalent in every place the port slices,
//     because each slice boundary is anchored to a substring of the same
//     string (a prefix or a `$`-anchored suffix match).
//  3. JSON output: fields that can be explicitly set to an empty value by the
//     original code are preserved. In particular `episodesRange.type` uses a
//     *string so that the empty-string value produced by e.g. "[01-12v2]"
//     (version stripped, leaving "") survives serialization, matching the
//     original output. All other optional fields use omitempty as before.
//  4. Faithful bug-for-bug behavior: the port intentionally reproduces
//     original quirks, including:
//     - WrappedVolumesRangeRE writes `volumesRange.to = vol1` (the original
//     writes the *from* value into `to` twice).
//     - `parseFansub` keeps the "jibaketa" hack and the `Vol|vol|Volume|volume`
//     case-sensitive alternation.
//     - `matchEpiodes` treats "Movie vN" as `type: "Movie"` plus a version.
//  5. Unused exports: `parseSuffixTextInlineMultipleTags` and
//     `parseSingleTitle` are ported for completeness although the original
//     package never calls them.
//  6. The `fansub` casing is preserved exactly as the original enum values
//     (e.g. "雪飄工作室(FLsnow)", "Prejudice-Studio"), so callers pass the
//     same strings as the TypeScript `Fansub` enum.
package anipar
